### ISSUE TITLE
Ukraine: Unable to play tracks

### ISSUE THREAD

**Issue by Menelion** [beqabeqa473/GozalMusicMini#4]
Using version 0.3.

**Steps to reproduce**:

1. Open the player.
2. Authorize with your VK login.
3. Try to play one of your audios or a found track after a successful search.

**Expected result**: The track should start playing.  
**Actual result**: The play becomes totally unresponsive, JAWS crashes when trying to play a track for the first time (JAWS crash not reproducible afterwards). After three minutes or so (4 Gb RAM) the following message box appears:

```
Error
Cannot play track at this timeSystem.Runtime.InteropServices.COMException (0x80072EE2): 
Exception from HRESULT: 0x80072EE2
   at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader.Init(MediaFoundationReaderSettings initialSettings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file)
   at NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
   at NAudio.Wave.AudioFileReader..ctor(String fileName)
   at GozalMusicMini.MainForm.PlaySound(String filename)
   at GozalMusicMini.MainForm.Playfile()
```

**Comment by beqabeqa473** [comment]
hi.

it seems, even direct vk links are blocked in ukraine.

ok, i will readd proxy then.

thanks for catching.

**Comment by beqabeqa473** [comment]
readded proxy support in version 0.4

please try this version and sorry for the delay
now it should work also in ukraine
